
// This file has been generated by the GUI designer. Do not modify.
namespace DroneClient
{
	public partial class submittask
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DroneClient.submittask
			this.Name = "DroneClient.submittask";
			this.Title = global::Mono.Unix.Catalog.GetString ("submittask");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
